// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14(""), bytes16("UserBets")))
);
ResourceId constant UserBetsTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0028030104042000000000000000000000000000000000000000000000000000
);

struct UserBetsData {
  uint32 id;
  uint32 betOptionId;
  uint256 amount;
  string option;
}

library UserBets {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.UINT32;
    _keySchema[1] = SchemaType.ADDRESS;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](4);
    _valueSchema[0] = SchemaType.UINT32;
    _valueSchema[1] = SchemaType.UINT32;
    _valueSchema[2] = SchemaType.UINT256;
    _valueSchema[3] = SchemaType.STRING;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "betId";
    keyNames[1] = "userId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "id";
    fieldNames[1] = "betOptionId";
    fieldNames[2] = "amount";
    fieldNames[3] = "option";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get id.
   */
  function getId(uint32 betId, address userId) internal view returns (uint32 id) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get id.
   */
  function _getId(uint32 betId, address userId) internal view returns (uint32 id) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set id.
   */
  function setId(uint32 betId, address userId, uint32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((id)), _fieldLayout);
  }

  /**
   * @notice Set id.
   */
  function _setId(uint32 betId, address userId, uint32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((id)), _fieldLayout);
  }

  /**
   * @notice Get betOptionId.
   */
  function getBetOptionId(uint32 betId, address userId) internal view returns (uint32 betOptionId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get betOptionId.
   */
  function _getBetOptionId(uint32 betId, address userId) internal view returns (uint32 betOptionId) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set betOptionId.
   */
  function setBetOptionId(uint32 betId, address userId, uint32 betOptionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((betOptionId)), _fieldLayout);
  }

  /**
   * @notice Set betOptionId.
   */
  function _setBetOptionId(uint32 betId, address userId, uint32 betOptionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((betOptionId)), _fieldLayout);
  }

  /**
   * @notice Get amount.
   */
  function getAmount(uint32 betId, address userId) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function _getAmount(uint32 betId, address userId) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set amount.
   */
  function setAmount(uint32 betId, address userId, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _setAmount(uint32 betId, address userId, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Get option.
   */
  function getOption(uint32 betId, address userId) internal view returns (string memory option) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get option.
   */
  function _getOption(uint32 betId, address userId) internal view returns (string memory option) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set option.
   */
  function setOption(uint32 betId, address userId, string memory option) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((option)));
  }

  /**
   * @notice Set option.
   */
  function _setOption(uint32 betId, address userId, string memory option) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((option)));
  }

  /**
   * @notice Get the length of option.
   */
  function lengthOption(uint32 betId, address userId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of option.
   */
  function _lengthOption(uint32 betId, address userId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of option.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemOption(uint32 betId, address userId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of option.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemOption(uint32 betId, address userId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to option.
   */
  function pushOption(uint32 betId, address userId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to option.
   */
  function _pushOption(uint32 betId, address userId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from option.
   */
  function popOption(uint32 betId, address userId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from option.
   */
  function _popOption(uint32 betId, address userId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of option at `_index`.
   */
  function updateOption(uint32 betId, address userId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of option at `_index`.
   */
  function _updateOption(uint32 betId, address userId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint32 betId, address userId) internal view returns (UserBetsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint32 betId, address userId) internal view returns (UserBetsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 betId,
    address userId,
    uint32 id,
    uint32 betOptionId,
    uint256 amount,
    string memory option
  ) internal {
    bytes memory _staticData = encodeStatic(id, betOptionId, amount);

    PackedCounter _encodedLengths = encodeLengths(option);
    bytes memory _dynamicData = encodeDynamic(option);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 betId,
    address userId,
    uint32 id,
    uint32 betOptionId,
    uint256 amount,
    string memory option
  ) internal {
    bytes memory _staticData = encodeStatic(id, betOptionId, amount);

    PackedCounter _encodedLengths = encodeLengths(option);
    bytes memory _dynamicData = encodeDynamic(option);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint32 betId, address userId, UserBetsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.id, _table.betOptionId, _table.amount);

    PackedCounter _encodedLengths = encodeLengths(_table.option);
    bytes memory _dynamicData = encodeDynamic(_table.option);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint32 betId, address userId, UserBetsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.id, _table.betOptionId, _table.amount);

    PackedCounter _encodedLengths = encodeLengths(_table.option);
    bytes memory _dynamicData = encodeDynamic(_table.option);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 id, uint32 betOptionId, uint256 amount) {
    id = (uint32(Bytes.slice4(_blob, 0)));

    betOptionId = (uint32(Bytes.slice4(_blob, 4)));

    amount = (uint256(Bytes.slice32(_blob, 8)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    PackedCounter _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory option) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    option = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (UserBetsData memory _table) {
    (_table.id, _table.betOptionId, _table.amount) = decodeStatic(_staticData);

    (_table.option) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint32 betId, address userId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint32 betId, address userId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 id, uint32 betOptionId, uint256 amount) internal pure returns (bytes memory) {
    return abi.encodePacked(id, betOptionId, amount);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory option) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(option).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory option) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((option)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 id,
    uint32 betOptionId,
    uint256 amount,
    string memory option
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(id, betOptionId, amount);

    PackedCounter _encodedLengths = encodeLengths(option);
    bytes memory _dynamicData = encodeDynamic(option);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint32 betId, address userId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(betId));
    _keyTuple[1] = bytes32(uint256(uint160(userId)));

    return _keyTuple;
  }
}
