// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { UserBets, UserBetsData, UserBetsTableId } from "./tables/UserBets.sol";
import { Topics, TopicsData, TopicsTableId } from "./tables/Topics.sol";
import { Bets, BetsData, BetsTableId } from "./tables/Bets.sol";
import { BetOptionTotals, BetOptionTotalsData, BetOptionTotalsTableId } from "./tables/BetOptionTotals.sol";
