// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TopicsData } from "./../tables/Topics.sol";

/**
 * @title INewTopicSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INewTopicSystem {
  function addTopic(string memory name, string memory genre, string memory description) external;

  function getTopic(uint32 id) external view returns (TopicsData memory);
}
