// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { BetsData } from "./../index.sol";

/**
 * @title IPredictionSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPredictionSystem {
  function createNewBet(
    string memory Question,
    string memory Description,
    uint32 Topic
  ) external returns (BetsData memory);

  function endBet(uint32 betId) external;

  function payoutWinners(uint32 betId) external;
}
