// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { UserData } from "./../index.sol";

/**
 * @title IUserSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUserSystem {
  function addNewUser(address did, string memory userName) external;

  function getUser(address did) external view returns (UserData memory);

  function modifyUser(address did, UserData memory newUserData) external;
}
