// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IVotingSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVotingSystem {
  function VoteForOption(uint32 OptionId, uint256 Amount) external returns (bool);

  function ReferralVoteForOption(uint32 OptionId, uint256 Amount, address referree) external returns (bool);
}
